
events {}

http{
    include /opt/homebrew/etc/nginx/mime.types;
    server{
        listen 8081;
        root /opt/homebrew/var/www/ngo-frontend;

        location /{
            try_files $uri $uri/ /index.html;
        }
        location /api/{
            proxy_pass http://localhost:5001;
        }
        location /store/{
            proxy_pass http://localhost:8082/store/;
        }
    }
}